
const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    VENDOR:"VENDOR",
    USER: "USER"
}
const CAN_RESOURCE = {
    SYSTEM: "SYSTEM",
    CATEGORY: "CATEGORY",
    USER: "USER"
}
const CAN_ACTION = {
    READ: "READ",
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE"
}
export {ROLES,CAN_RESOURCE,CAN_ACTION}